markdown: redcarpet
highlighter: null
permalink: /:title

url: http://oddbjorn.steffensen.net/
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
