# Site settings
title: Security Rebooted
email: oddbjorn@tricknology.org
description: "Random ruminations on all things information security."
baseurl: ""
url: "http://oddbjorn.steffensen.net"

# Build settings
markdown: kramdown
permalink: pretty
