# Site settings
title: Security Rebooted
email: oddbjorn@tricknology.org
description: "Random ruminations on all things information security related. Or not."
baseurl: ""
url: "http://oddbjorn.github.io"

# Build settings
markdown: kramdown
permalink: pretty
